version: '3.7'

services:
  app:
    build:
      context: .
    container_name: sandy_container
    image: timster01/sandy
    restart: unless-stopped
    environment:
      - NODE_ENV
      - slackWebAppHook
      - slackAppBotAccessToken
      - slackAppId
      - slackAppWorkspaceId
      - slackAppToken
    ports:
      - 8000 #exposes correct ports