version: '3.7'

services:
  app:
    build:
      context: .
    container_name: sandy_container
    environment:
      - NODE_ENV
      - THISAPP
      - PORT
      - slackWebAppHook
      - slackAppBotAccessToken
      - slackAppId
      - slackAppWorkspaceId
      - slackAppToken
    ports:
      - ${PORT}:${PORT} #exposes correct ports