version: '3'

services:
  app:
    build: .
    command: node app.js
    container_name: sandy_container
    environment:
      - THISAPP="http://localhost"
      - PORT=8000
    ports:
      - 8000:8000